package com.yqwl.pojo;

import java.io.Serializable;

public class Brand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.vision
     *
     * @mbggenerated
     */
    private String vision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.progress
     *
     * @mbggenerated
     */
    private String progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.details_img
     *
     * @mbggenerated
     */
    private String details_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.home_page
     *
     * @mbggenerated
     */
    private Integer home_page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_brand
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.id
     *
     * @return the value of t_brand.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.id
     *
     * @param id the value for t_brand.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.name
     *
     * @return the value of t_brand.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.name
     *
     * @param name the value for t_brand.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.introduction
     *
     * @return the value of t_brand.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.introduction
     *
     * @param introduction the value for t_brand.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.vision
     *
     * @return the value of t_brand.vision
     *
     * @mbggenerated
     */
    public String getVision() {
        return vision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.vision
     *
     * @param vision the value for t_brand.vision
     *
     * @mbggenerated
     */
    public void setVision(String vision) {
        this.vision = vision == null ? null : vision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.progress
     *
     * @return the value of t_brand.progress
     *
     * @mbggenerated
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.progress
     *
     * @param progress the value for t_brand.progress
     *
     * @mbggenerated
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.details_img
     *
     * @return the value of t_brand.details_img
     *
     * @mbggenerated
     */
    public String getDetails_img() {
        return details_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.details_img
     *
     * @param details_img the value for t_brand.details_img
     *
     * @mbggenerated
     */
    public void setDetails_img(String details_img) {
        this.details_img = details_img == null ? null : details_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.img
     *
     * @return the value of t_brand.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.img
     *
     * @param img the value for t_brand.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.status
     *
     * @return the value of t_brand.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.status
     *
     * @param status the value for t_brand.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.home_page
     *
     * @return the value of t_brand.home_page
     *
     * @mbggenerated
     */
    public Integer getHome_page() {
        return home_page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.home_page
     *
     * @param home_page the value for t_brand.home_page
     *
     * @mbggenerated
     */
    public void setHome_page(Integer home_page) {
        this.home_page = home_page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.rank
     *
     * @return the value of t_brand.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.rank
     *
     * @param rank the value for t_brand.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Brand other = (Brand) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIntroduction() == null ? other.getIntroduction() == null : this.getIntroduction().equals(other.getIntroduction()))
            && (this.getVision() == null ? other.getVision() == null : this.getVision().equals(other.getVision()))
            && (this.getProgress() == null ? other.getProgress() == null : this.getProgress().equals(other.getProgress()))
            && (this.getDetails_img() == null ? other.getDetails_img() == null : this.getDetails_img().equals(other.getDetails_img()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getHome_page() == null ? other.getHome_page() == null : this.getHome_page().equals(other.getHome_page()))
            && (this.getRank() == null ? other.getRank() == null : this.getRank().equals(other.getRank()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
        result = prime * result + ((getVision() == null) ? 0 : getVision().hashCode());
        result = prime * result + ((getProgress() == null) ? 0 : getProgress().hashCode());
        result = prime * result + ((getDetails_img() == null) ? 0 : getDetails_img().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getHome_page() == null) ? 0 : getHome_page().hashCode());
        result = prime * result + ((getRank() == null) ? 0 : getRank().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", introduction=").append(introduction);
        sb.append(", vision=").append(vision);
        sb.append(", progress=").append(progress);
        sb.append(", details_img=").append(details_img);
        sb.append(", img=").append(img);
        sb.append(", status=").append(status);
        sb.append(", home_page=").append(home_page);
        sb.append(", rank=").append(rank);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}