package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Introduce implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.wishes
     *
     * @mbggenerated
     */
    private String wishes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.E_mail
     *
     * @mbggenerated
     */
    private String e_mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.QR_code
     *
     * @mbggenerated
     */
    private String QR_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.QQ
     *
     * @mbggenerated
     */
    private Long QQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_introduce.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_introduce
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.id
     *
     * @return the value of t_introduce.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.id
     *
     * @param id the value for t_introduce.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.content
     *
     * @return the value of t_introduce.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.content
     *
     * @param content the value for t_introduce.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.wishes
     *
     * @return the value of t_introduce.wishes
     *
     * @mbggenerated
     */
    public String getWishes() {
        return wishes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.wishes
     *
     * @param wishes the value for t_introduce.wishes
     *
     * @mbggenerated
     */
    public void setWishes(String wishes) {
        this.wishes = wishes == null ? null : wishes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.E_mail
     *
     * @return the value of t_introduce.E_mail
     *
     * @mbggenerated
     */
    public String getE_mail() {
        return e_mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.E_mail
     *
     * @param e_mail the value for t_introduce.E_mail
     *
     * @mbggenerated
     */
    public void setE_mail(String e_mail) {
        this.e_mail = e_mail == null ? null : e_mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.QR_code
     *
     * @return the value of t_introduce.QR_code
     *
     * @mbggenerated
     */
    public String getQR_code() {
        return QR_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.QR_code
     *
     * @param QR_code the value for t_introduce.QR_code
     *
     * @mbggenerated
     */
    public void setQR_code(String QR_code) {
        this.QR_code = QR_code == null ? null : QR_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.QQ
     *
     * @return the value of t_introduce.QQ
     *
     * @mbggenerated
     */
    public Long getQQ() {
        return QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.QQ
     *
     * @param QQ the value for t_introduce.QQ
     *
     * @mbggenerated
     */
    public void setQQ(Long QQ) {
        this.QQ = QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_introduce.time
     *
     * @return the value of t_introduce.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_introduce.time
     *
     * @param time the value for t_introduce.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_introduce
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Introduce other = (Introduce) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getWishes() == null ? other.getWishes() == null : this.getWishes().equals(other.getWishes()))
            && (this.getE_mail() == null ? other.getE_mail() == null : this.getE_mail().equals(other.getE_mail()))
            && (this.getQR_code() == null ? other.getQR_code() == null : this.getQR_code().equals(other.getQR_code()))
            && (this.getQQ() == null ? other.getQQ() == null : this.getQQ().equals(other.getQQ()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_introduce
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getWishes() == null) ? 0 : getWishes().hashCode());
        result = prime * result + ((getE_mail() == null) ? 0 : getE_mail().hashCode());
        result = prime * result + ((getQR_code() == null) ? 0 : getQR_code().hashCode());
        result = prime * result + ((getQQ() == null) ? 0 : getQQ().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_introduce
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", wishes=").append(wishes);
        sb.append(", e_mail=").append(e_mail);
        sb.append(", QR_code=").append(QR_code);
        sb.append(", QQ=").append(QQ);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}