package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Merchant implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.first_show
     *
     * @mbggenerated
     */
    private Integer first_show;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.order_time
     *
     * @mbggenerated
     */
    private Date order_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_merchant
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.id
     *
     * @return the value of t_merchant.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.id
     *
     * @param id the value for t_merchant.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.title
     *
     * @return the value of t_merchant.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.title
     *
     * @param title the value for t_merchant.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.img
     *
     * @return the value of t_merchant.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.img
     *
     * @param img the value for t_merchant.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.status
     *
     * @return the value of t_merchant.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.status
     *
     * @param status the value for t_merchant.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.time
     *
     * @return the value of t_merchant.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.time
     *
     * @param time the value for t_merchant.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.first_show
     *
     * @return the value of t_merchant.first_show
     *
     * @mbggenerated
     */
    public Integer getFirst_show() {
        return first_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.first_show
     *
     * @param first_show the value for t_merchant.first_show
     *
     * @mbggenerated
     */
    public void setFirst_show(Integer first_show) {
        this.first_show = first_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.order_time
     *
     * @return the value of t_merchant.order_time
     *
     * @mbggenerated
     */
    public Date getOrder_time() {
        return order_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.order_time
     *
     * @param order_time the value for t_merchant.order_time
     *
     * @mbggenerated
     */
    public void setOrder_time(Date order_time) {
        this.order_time = order_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.content
     *
     * @return the value of t_merchant.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.content
     *
     * @param content the value for t_merchant.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Merchant other = (Merchant) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getFirst_show() == null ? other.getFirst_show() == null : this.getFirst_show().equals(other.getFirst_show()))
            && (this.getOrder_time() == null ? other.getOrder_time() == null : this.getOrder_time().equals(other.getOrder_time()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getFirst_show() == null) ? 0 : getFirst_show().hashCode());
        result = prime * result + ((getOrder_time() == null) ? 0 : getOrder_time().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", img=").append(img);
        sb.append(", status=").append(status);
        sb.append(", time=").append(time);
        sb.append(", first_show=").append(first_show);
        sb.append(", order_time=").append(order_time);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}