package com.yqwl.dao;

import com.yqwl.pojo.ColumnPrograma;

import java.util.List;

public interface ColumnProgramaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    int insert(ColumnPrograma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    int insertSelective(ColumnPrograma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    ColumnPrograma selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ColumnPrograma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column_programa
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ColumnPrograma record);

    List<ColumnPrograma> showColumn();
}