package com.yqwl.dao;

import com.yqwl.pojo.Elegant;

import java.util.List;

public interface ElegantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    int insert(Elegant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    int insertSelective(Elegant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    Elegant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Elegant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_elegant
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Elegant record);

    /**
     * 查询
     * @param type
     * @return
     */
    List<Elegant> queryElegantList(Integer type);
}