package com.yqwl.dao;

import com.yqwl.pojo.Employment;

import java.util.List;

public interface EmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    int insert(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    int insertSelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    Employment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Employment record);

    /**
     *
     * 查询招聘列表
     */
    List<Employment> employmentList();
}