package com.yqwl.dao;

import com.yqwl.pojo.Investment;

import java.util.List;

public interface InvestmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    int insert(Investment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    int insertSelective(Investment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    Investment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Investment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_investment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Investment record);

    List<Investment> investmentList();
}