package com.yqwl.dao;

import com.yqwl.pojo.MallIntroduce;

import java.util.List;

public interface MallIntroduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int insert(MallIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int insertSelective(MallIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    MallIntroduce selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MallIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_introduce
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallIntroduce record);

    List<MallIntroduce> showMallIntroduce();

    MallIntroduce showFrontMallIntroduce();
}