package com.yqwl.dao;

import com.yqwl.pojo.Supervisor;
import org.apache.ibatis.annotations.Param;

public interface SupervisorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    int insert(Supervisor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    int insertSelective(Supervisor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    Supervisor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Supervisor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supervisor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Supervisor record);

    Supervisor findByUsernamePwd(@Param("username") String username, @Param("password") String passwords);
}